// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oakestra")
	ScopeName = "github.com/smnzlnsk/opentelemetry-components/processor/oakestraprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
