
CURL=curl

REPO=github.com/smnzlnsk/opentelemetry-components
GOPROXY=https://proxy.golang.org

BACKEND_EXPORTER_MODULE=exporters/backend
MQTT_RECEIVER_MODULE=receivers/mqttreceiver
MQTT_EXPORTER_MODULE=exporters/mqttexporter

VERSION=v0.0.0
BACKEND_EXPORTER_VERSION=v0.0.0
MQTT_RECEIVER_VERSION=v0.0.0
MQTT_EXPORTER_VERSION=v0.0.0

.PHONY: check-proxy
check-proxy:
	$(CURL) $(GOPROXY)/$(REPO)/$(BACKEND_EXPORTER_MODULE)/@v/$(BACKEND_EXPORTER_VERSION).info
	$(CURL) $(GOPROXY)/$(REPO)/$(MQTT_EXPORTER_MODULE)/@v/$(MQTT_EXPORTER_VERSION).info
	$(CURL) $(GOPROXY)/$(REPO)/$(MQTT_RECEIVER_MODULE)/@v/$(MQTT_RECEIVER_VERSION).info

