// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("mqtt")
	ScopeName = "github.com/smnzlnsk/opentelemetry-components/exporter/mqttexporter"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
